[project]
name = "FurBot"
version = "0.1.0"
description = "FurBot"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "Satori", module_name = "nonebot.adapters.satori" }
]
plugins = []
plugin_dirs = []
builtin_plugins = ["echo"]
